name: Deploy to EC2

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Debug Info
      run: |
        echo "Actor: $GITHUB_ACTOR"
        echo "Ref: $GITHUB_REF"
        echo "SHA: $GITHUB_SHA"

    - name: Create PEM file
      run: |
        echo "${{ secrets.EC2_KEY }}" > key.pem
        chmod 400 key.pem

    - name: Upload .env to EC2
      run: |
        echo "${{ secrets.ENV_FILE }}" > .env
        scp -o StrictHostKeyChecking=no -i key.pem .env ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:/home/ubuntu/FOREST_BE/.env

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} << 'EOF'
          export NVM_DIR="$HOME/.nvm"
          source "$NVM_DIR/nvm.sh"
          cd ~/FOREST_BE
          git pull origin main
          npm install
          pm2 restart forest-be --update-env || node src/index.js &
        EOF
