name: Deploy to EC2

on:
  push:
    branches:
      - main   # main 브랜치에 push되면만 실행됨 (dev → main 머지 포함)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Create PEM file
      run: |
        echo "${{ secrets.EC2_KEY }}" > key.pem
        chmod 400 key.pem


    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} << 'EOF'
          cd ~/FOREST_BE
          git pull origin main
          npm install
          pm2 restart all || node src/index.js &
        EOF
